#!/usr/bin/env python3
"""
打开浏览器登录 bilibili.com，将 Cookie 写入 cookies.txt（Netscape 格式），供 yt-dlp / video_collector 使用。

用法：
  python bilibili_login.py
  ./run.sh --login
"""

from __future__ import annotations

import asyncio
import sys
from pathlib import Path

SCRIPT_DIR = Path(__file__).resolve().parent
COOKIES_OUT = SCRIPT_DIR / "cookies.txt"

BILI_HOME = "https://www.bilibili.com"


def cookies_to_netscape(cookies: list[dict]) -> str:
    """Playwright cookie dict → Netscape 文本（yt-dlp 可读）。"""
    lines = [
        "# Netscape HTTP Cookie File",
        "# https://curl.haxx.se/rfc/cookie_spec.html",
        "# Generated by video_collector bilibili_login — do not edit by hand.",
        "",
    ]
    for c in cookies:
        domain = (c.get("domain") or "").strip()
        if "bilibili" not in domain.lower():
            continue
        path = c.get("path") or "/"
        secure = "TRUE" if c.get("secure") else "FALSE"
        name = c.get("name") or ""
        value = c.get("value") or ""
        include = "TRUE" if domain.startswith(".") else "FALSE"
        exp = c.get("expires")
        if exp is None or exp < 0:
            expiration = 0
        else:
            expiration = int(exp)
        lines.append(
            f"{domain}\t{include}\t{path}\t{secure}\t{expiration}\t{name}\t{value}"
        )
    return "\n".join(lines) + "\n"


async def _do_login() -> None:
    from playwright.async_api import async_playwright

    print("正在打开 Chromium，请在页面内完成 B 站登录（扫码或手机/密码）。")
    print(f"登录成功后回到此终端，按 Enter 将 Cookie 写入：{COOKIES_OUT}\n")

    async with async_playwright() as p:
        browser = await p.chromium.launch(
            headless=False,
            args=["--disable-blink-features=AutomationControlled"],
        )
        context = await browser.new_context(
            user_agent=(
                "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) "
                "AppleWebKit/537.36 (KHTML, like Gecko) "
                "Chrome/120.0.0.0 Safari/537.36"
            ),
            viewport={"width": 1280, "height": 800},
        )
        page = await context.new_page()
        await page.goto(BILI_HOME, wait_until="domcontentloaded", timeout=60000)

        try:
            input("登录完成后按 Enter 保存 Cookie… ")
        except (EOFError, KeyboardInterrupt):
            print("\n已取消。")
            await browser.close()
            sys.exit(1)

        cookies = await context.cookies()
        await browser.close()

    if not cookies:
        print("未获取到任何 Cookie，请重试。")
        sys.exit(1)

    bili_cookies = [c for c in cookies if "bilibili" in (c.get("domain") or "").lower()]
    if not bili_cookies:
        print("警告：未筛出 bilibili 域名 Cookie，仍将写入全部上下文 Cookie。")
        bili_cookies = cookies

    COOKIES_OUT.write_text(cookies_to_netscape(bili_cookies), encoding="utf-8")
    print(f"\n已写入 {len(bili_cookies)} 条相关 Cookie → {COOKIES_OUT}")
    print("接下来可执行：./run.sh --dry-run 'https://www.bilibili.com/video/BV...'")


def main() -> None:
    asyncio.run(_do_login())


if __name__ == "__main__":
    main()
